version: '3.8'

services:
  crewai-bot:
    build: .
    container_name: crewai-bot
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    
  # 선택적: 데이터베이스 (필요시 활성화)
  # postgres:
  #   image: postgres:15
  #   container_name: crewai-db
  #   environment:
  #     POSTGRES_DB: crewai_bot
  #     POSTGRES_USER: bot_user
  #     POSTGRES_PASSWORD: bot_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  postgres_data:

# **더미가 아닌 실제 도커 컴포즈 설정입니다**
